TTRPGEngine/TTRPGEngine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("", RedirectView.as_view(url='/npc/')),
    path('admin/', admin.site.urls),
    path('npc/', include('npc.urls')),
    path("home/", include('accounts.urls')),
] + debug_toolbar_urls()

TTRPGEngine/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account_home/', views.account_home, name='account_home'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="password_change.html"), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/templates/"), name='password_reset'),
    #path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/templates/"), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/templates/"), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/templates/"), name='password_reset_complete')
    path('about/', views.about, name='about')
]

TTRPGEngine/npc/urls.py
from django.urls import path

from . import views

app_name = "npc"

urlpatterns = [
    path('', views.Rooster, name="character-select"),
    path('character', views.character, name="character")
]

TTRPGEngine/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
     <header>
        <h1>{% block header_title %}My Website{% endblock %}</h1>
        <nav>
            <a href="{% url 'accounts:account_home' %}" class="button">Account</a>
            <form method="post" style='display:inline;' action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                <button type="submit" class="button">logout</button>
            </form>
            <button id="theme-toggle" class="button">Toggle Dark Mode</button>
        </nav>
     </header>

     <!-- Main content block -->
     {% block content %}
     <!-- Default content can go here (optional) -->
     {% endblock %}

     <footer>
        <p>&copy; 2023 My Website. All rights reserved.</p>
     </footer>

     <script src="{% static 'script.js' %}"></script>
</body>
</html>

TTRPGEngine/templates/footer.html
<footer>
    <p>&copy; 2023 My Website. All rights reserved.</p>
</footer>

TTRPGEngine/templates/header.html
<header>
    <h1>{% block header_title %}My Website{% endblock %}</h1>
    <nav>
        <a href="{% url 'downloader:home' %}" class="button">Home</a>

        <button id="theme-toggle" class="button">Toggle Dark Mode</button>
    </nav>
</header>