TTRPGEngine/TTRPGEngine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("", RedirectView.as_view(url='/npc/')),
    path('admin/', admin.site.urls),
    path('npc/', include('npc.urls')),
    path("home/", include('accounts.urls')),
] + debug_toolbar_urls()

TTRPGEngine/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account_home/', views.account_home, name='account_home'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="password_change.html"), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path('password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/templates/"), name='password_reset'),
    #path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/templates/"), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/templates/"), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/templates/"), name='password_reset_complete')
    path('about/', views.about, name='about')
]

TTRPGEngine/npc/urls.py
from django.urls import path

from . import views

app_name = "npc"

urlpatterns = [
    path('', views.Rooster, name="character-select"),
    path('character', views.character, name="character")
]

TTRPGEngine/accounts/models.py
from django.db import models

# Create your models here.

TTRPGEngine/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_not_required
from django.contrib.messages.context_processors import messages
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm

def account_home(request):
    return render(request, 'account_home.html')

@login_not_required
def register(request):

    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages(request).success(request, 'You have singed up successfully.')
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'register.html', {'form': form})

@login_not_required
def about(request):
    return render(request, 'about.html')

TTRPGEngine/accounts/templates/about.html
{% extends "base.html" %}

{% block title %}
  Welcome to YTDLManger
{% endblock %}

{% block header_title %}Home{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="card">
                <p>Screw you for now</p>
                <p>Seriously, under development</p>

            </div>
        </div>
    </section>
{% endblock %}

TTRPGEngine/accounts/templates/account_home.html
{% extends "base.html" %}

{% block title %}
  Account
{% endblock %}

{% block header_title %}
    Home
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="card">
                <a href="{% url 'accounts:password_change' %}" class="button">Change Password</a>
            </div>
        </div>
    </section>
{% endblock %}

TTRPGEngine/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}
  Account
{% endblock %}

{% block header_title %}Welcome{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="card">
                <h2>Log In</h2>
                  <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Log In</button>
                  </form>
                <a href="{% url 'accounts:register' %}">Need to sign up instead?</a>
            </div>

            <div class="card">
                <h2>About Us</h2>
                <p>This is a website</p>
                <a href="{% url 'accounts:about' %}" class="button">Learn More</a>
            </div>
        </div>
    </section>
{% endblock %}

TTRPGEngine/accounts/templates/password_change.html
{% extends "base.html" %}

{% block title %}
  Welcome to YTDLManger
{% endblock %}

{% block header_title %}Home{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="card">
                <h2>Change Password</h2>
                  <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Log In</button>
                  </form>
            </div>
        </div>
    </section>
{% endblock %}

TTRPGEngine/accounts/templates/register.html
{% extends "base.html" %}

{% block title %}
  Account
{% endblock %}

{% block header_title %}
    Home
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="card">
                <h2>Sign Up</h2>
                  <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Sign Up</button>
                  </form>
                <a href="{% url 'accounts:login' %}">Need to Log In instead?</a>
            </div>
        </div>
    </section>
{% endblock %}